CREATE TABLE BOOK(
ISBN BIGINT,
TITLE VARCHAR(100),
AUTHOR VARCHAR(100),
PUBLISHED_DATE DATE,
PRIMARY KEY(ISBN)
);

CREATE TABLE REVIEW(
REVIEW_ID BIGSERIAL,
REVIEWER_NAME VARCHAR(100),
CONTENT VARCHAR(100),
RATING DECIMAL,
PUBLISHED_DATE DATE,
BOOK_ID BIGINT,
PRIMARY KEY(REVIEW_ID),
FOREIGN KEY(BOOK_ID) REFERENCES BOOK(ISBN) 
);